### ISSUE TITLE
Repeat one song all the time

### ISSUE THREAD

**Issue by stefancvetkovic** [fondberg/spotcast#120]
```
  - service: spotcast.start
    data:
      device_name: Denon AVR-X2400H
      entity_id: media_player.spotify_stefan
      uri: 'spotify:playlist:37i9dQZF1DX9loJQLuEvap'
      force_playback: true
      random_song: true
      shuffle: true
```
With this params, when I call service spotcast.star, Im getting always different song which is OK, but that song has infinite loop, its like it is set repeat mode:on but its not?
