### ISSUE TITLE
shuffle and repeat not honored when using force_playback=true and empty uri

### ISSUE THREAD

**Issue by logan893** [fondberg/spotcast#132]
Example: Calling spotcast.start as a tap_action on a button card
```
        tap_action:
          action: call-service
          service: spotcast.start
          service_data:
            entity_id: media_player.all_speakers
            device_name: All Speakers
            force_playback: true
            shuffle: true
            repeat: context
```

The shuffle and repeat options are not sent to Spotify. This combination of no URI and force_playback=true doesn't include these two options.

To fix this I moved the shuffle and repeat actions from the play function to the end of the start_casting function.

```
bash-5.0# diff __init__.py.original __init__.py
--- __init__.py.original
+++ __init__.py
@@ -255,16 +255,6 @@
                 random_song,
             )
             client.start_playback(**kwargs)
-        if shuffle or repeat:
-            time.sleep(3)
-            if shuffle:
-                _LOGGER.debug("Turning shuffle on")
-                time.sleep(2)
-                client.shuffle(state=shuffle, device_id=spotify_device_id)
-            if repeat:
-                _LOGGER.debug("Turning repeat on")
-                time.sleep(2)
-                client.repeat(state=repeat, device_id=spotify_device_id)

     def getSpotifyConnectDeviceId(client, device_name):
         devices_available = client.devices()
@@ -312,6 +302,17 @@
             client.transfer_playback(device_id=spotify_device_id, force_play=force_playback)
         else:
             play(client, spotify_device_id, uri, random_song, repeat, shuffle, position)
+
+        if shuffle or repeat:
+            time.sleep(3)
+            if shuffle:
+                _LOGGER.debug("Turning shuffle on")
+                time.sleep(2)
+                client.shuffle(state=shuffle, device_id=spotify_device_id)
+            if repeat:
+                _LOGGER.debug("Turning repeat on")
+                time.sleep(2)
+                client.repeat(state=repeat, device_id=spotify_device_id)

     # Register websocket and service
     hass.components.websocket_api.async_register_command(
bash-5.0#
```
