### ISSUE TITLE
Currently active device

### ISSUE THREAD

**Issue by kongo09** [fondberg/spotcast#155]
Is there a way to have a sensor tell me which device is currently active?

As a user, I would like to be able to convey state in the interface, highlighting the active device in a choice of devices.

**Comment by kongo09** [comment]
Stupid me - I should be able to get this from the active media_player...

**Comment by kongo09** [comment]
For reference if someone else is looking for the same thing: I used the great `custom:button-card` with a template state to do this:
```
type: 'custom:button-card'
name: Wohnzimmer
tap_action:
  action: call-service
  service: spotcast.start
  service_data:
    device_name: Wohnzimmer
state:
  - operator: template
    value: |
      [[[
        return states['media_player.spotify'].attributes.source == 'Wohnzimmer'
      ]]]
    styles:
      card:
        - background-color: var(--primary-text-color)
        - color: var(--card-background-color)
      name:
        - color: 'var(--mmp-accent-color, var(--accent-color))'
```
