### ISSUE TITLE
Playlist Sensor

### ISSUE THREAD

**Issue by jazzyisj** [fondberg/spotcast#158]
Would it be possible to have a sensor similar to the device sensor for playlists?

The use case for this is I have several media presets for various things (wake media, sleep media, arrive home media etc.)  which are used to launch spotify using the spotcast service. Currently I have to manually get the URI and put the playlist name and playlist URI in a template to populate an input select entity and play the associated playlist.

A sensor with a dictionary of the playlists retrieved by spotcast would facilitate the automation of this process and automatically keep the playlist list up to date in HA when they are changed in Spotify.

I see the API info in the readme, but I'm not sure what to do with that.  Perhaps an example for using the API would make this request redundant?

Example playlist template.

```
>
  {% if playlist == 'Shower Songs' %} spotify:playlist:37i9dQZF1DWSqmBTGDYngZ
  {% elif playlist == 'All Out 60s' %} spotify:playlist:37i9dQZF1DXaKIA8E7WcJj
  {% elif playlist == 'All Out 80s' %} spotify:playlist:37i9dQZF1DX4UtSsGT1Sbe
  {% endif %}
```
Thank you for taking the time to consider this.

**Comment by fondberg** [comment]
Sounds like a food idea. Ill see if i have some time soon to implement it

**Comment by fondberg** [comment]
It turns out I need to refactor spotcast quite a lot to implement this so I can't promise when this can happen but I will look into it.

**Comment by jazzyisj** [comment]
Just curious,  how does HA get the playlists, albums etc. for the media browser?  I've looked all over, I was hoping maybe they were storing them in the .storage folder but I don't see them there.  I tried mucking about in the code to figure it out and got lost pretty quick.

Do you think it is possible to use that same method to populate a playlist sensor for each Spotify account set up with Spotcast without having to do a major refactor?

**Comment by fondberg** [comment]
Hi @jazzyisj , been sick, sorry for the delay.
HA doesn't have knowledge about playlists. When you play something the core spotify mediaplayer gets the image and info from current playback.
The spotify-card gets its playlists from spotcast.

I'm probably going to deprecate the notion of accounts now that Spotify makes it more and more impossible to use the powerful token but it would be possible to add a playlist sensor to either spotcast or core spotify.

If it is added to core spotify the limit would be that it only supports the current users playlists or featured and not discover-weekly.

I can't guarantee that a PR would be merged though in core but that would be doable

**Comment by fondberg** [comment]
is anyone intreserest in this? I've refactored the code so I cab make this happen now

**Comment by jazzyisj** [comment]
Yes!  Please!

**Comment by fondberg** [comment]
What kind of data do you want and whatkindof config would you supply? 
Input: Multiaccount, playlist type, country code et.c.

Output would be what?

**Comment by jazzyisj** [comment]
So to recap, what I think would be quite useful is a sensor to expose the Spotify account(s) playlists and properties.  This is to provide automatically updated playback/playlist data to be used for Spotify playlist selection when not using the Spotcast card to initiate playback.

I created some template sensors to test out the concept and it worked out well.  It eliminates a bunch of repetitive templates based on manually updated playlists.

-  These are temporary template sensors I created to emulate what I would like to see Spotcast create for each account.
- The state is the current play status for that account (it could probably display account or play errors etc too?)
- The attributes values can be retrived directly through the Spotify API?  Here I just used sample values from related HA entities for testing concept.
- hassio is an actual Spotify user on my Spotify account and is used as the default account for Spotify in HA.
- The playlists attribute can contain both playlists and podcasts.
- I only included a json format attribute here for the example.  You could also include the key/value format similar to chromecast sensor devices_json/devices attributes.

```
- sensor:
    - name: Spotcast - Hassio
      unique_id: spotcast_hassio # acct name
      icon: mdi:spotify
      state: "{{ states('media_player.spotify_hassio') }}" # get from spotify API, also use to indicate acct error?
      attributes:
        source: "{{ state_attr('media_player.spotify_hassio','source') }}" # get from spotify API, current source
        playing: "{{ states('input_select.spotify_playlist') }}"  # get from spotify API, current play selection
        playlists: |
          [
            {
              "name":"Liked From Radio",
              "type":"playlist",
              "image":"https://i.scdn.co/image/ab67706f0000000304920365f870708dd107711e",
              "uri":"0rnrGv8vEW55kxi2GmjHPD"
            },
            {
              "name":"Classic Oldies",
              "type":"playlist",
              "image":"https://i.scdn.co/image/ab67706f0000000304920365f870708dd107711e",
              "uri":"37i9dQZF1DX56bqlsMxJYR"
            },
            {
              "name":"Have A Great Day!",
              "type":"playlist",
              "image":"https://i.scdn.co/image/ab67706f0000000304920365f870708dd107711e",
              "uri":"37i9dQZF1DX7KNKjOK0o75"
            },
            {
              "name":"Classic Rock Workout",
              "type":"playlist",
              "image":"https://i.scdn.co/image/ab67706f0000000304920365f870708dd107711e",
              "uri":"37i9dQZF1DWYNSm3Z3MxiM"
            },
            {
              "name":"Home Asssitant",
              "type":"show",
              "image":"https://i.scdn.co/image/ab67706f0000000304920365f870708dd107711e",
              "uri":"0rnrGv8vEW55kxi2GmjHPD"
            }
          ]

    - name: Spotcast - Jason
      unique_id: spotcast_jazzyisj
      icon: mdi:spotify
      state: "{{ states('media_player.spotify_jazzyisj') }}"
      attributes:
        source: "{{ state_attr('media_player.spotify_jazzyisj','source') }}"
        playing: "{{ states('input_select.spotify_playlist_jazzyisj') }}"
        playlists: |
          [
            {
              "name":"Liked From Radio",
              "type":"playlist",
              "image":"https://i.scdn.co/image/ab67706f0000000304920365f870708dd107711e",
              "uri":"0rnrGv8vEW55kxi2GmjHPD"
            },
            {
              "name":"Funk Rock",
              "type":"playlist",
              "image":"https://i.scdn.co/image/ab67706f0000000304920365f870708dd107711e",
              "uri":"37i9dQZF1DX23YPJntYMnh"
            },
            {
              "name":"Home Asssitant",
              "type":"show",
              "image":"https://i.scdn.co/image/ab67706f0000000304920365f870708dd107711e",
              "uri":"0rnrGv8vEW55kxi2GmjHPD"
            }
          ]

    - name: Spotcast - Sheri
      unique_id: spotcast_sherigagnon
      icon: mdi:spotify
      state: "{{ states('media_player.spotify_sherigagnon') }}"
      attributes:
        source: "{{ state_attr('media_player.spotify_sherigagnon','source') }}"
        playing: "{{ states('input_select.spotify_playlist_sherigagnon') }}"
        playlists: |
          [
            {
              "name":"Blues Classics",
              "type":"playlist",
              "image":"https://i.scdn.co/image/ab67706f0000000304920365f870708dd107711e",
              "uri":"37i9dQZF1DXd9rSDyQguIk"
            },
            {
              "name":"This Is Pink Floyd",
              "type":"playlist",
              "image":"https://i.scdn.co/image/ab67706f0000000304920365f870708dd107711e",
              "uri":"37i9dQZF1DXaQ34lqGBfrU"
            }
          ]

```
These are automations that populate and update the playlist input select helpers using the proposed spotcast sensor whenever the playlists attribute of the sensor changes (startup, whenever user modifies playlists on Spotify)
**Automatically populating these input selects was the catalyst for this request!**

```
- id: spotify_playlist_update_hassio
  alias: "[Spotify] Playlist Update Hassio"
  description: Update spotify playlist input.
  initial_state: true
  mode: restart
  trigger:
    - platform: homeassistant # probably unecessary because spotcast will update sensor playlists attribute on startup?
      event: start
    - platform: state
      entity_id: sensor.spotcast_hassio
      attribute: playlists
  action:
    - service: input_select.set_options
      target:
        entity_id: input_select.spotify_playlist_hassio
      data:
        options: >
          [{% for item in state_attr('sensor.spotcast_hassio','playlists')|from_json -%}
            "{{- item.name }}"{{ ',' if not loop.last -}}{% endfor %}]

- id: spotify_playlist_update_jazzyisj
  alias: "[Spotify] Playlist Update Jazzyisj"
  description: Update spotify playlist input.
  initial_state: true
  mode: restart
  trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: sensor.spotcast_jazzyisj
      attribute: playlists
  action:
    - service: input_select.set_options
      target:
        entity_id: input_select.spotify_playlist_jazzyisj
      data:
        options: >
          [{% for item in state_attr('sensor.spotcast_jazzyisj','playlists')|from_json -%}
            "{{- item.name }}"{{ ',' if not loop.last -}}{% endfor %}]

- id: spotify_playlist_update_sherigagnon
  alias: "[Spotify] Playlist Update Sherigagnon"
  description: Update spotify playlist input.
  initial_state: true
  mode: restart
  trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: sensor.spotcast_sherigagnon
      attribute: playlists
  action:
    - service: input_select.set_options
      target:
        entity_id: input_select.spotify_playlist_sherigagnon
      data:
        options: >
          [{% for item in state_attr('sensor.spotcast_sherigagnon','playlists')|from_json -%}
            "{{- item.name }}"{{ ',' if not loop.last -}}{% endfor %}]
```

This is how the spotcast sensor provides the URI to the service call for the currently selected playlist. It handles both playlists and podcasts.

```
- service: spotcast.start
    data:
    account: hassio
    device_name: Dining Room Speaker
    uri: >
        {% for item in state_attr('sensor.spotcast_hassio','playlists')|from_json -%}
          {% if item.name == states('input_select.spotify_playlist_hassio') %}
              spotify:{{ item.type }}:{{ item.uri }}
          {% endif %}
        {% endfor %}
```

**Comment by fondberg** [comment]
Hi!
what types of playlists should there be? Personal playlists I guess.

**Comment by jazzyisj** [comment]
Yes, I think that would make the most sense.   I guess basically what I'm looking for is to expose the data that would populate your Spotify Lovelace Card (the playlists most importantly, and also the current source/play state) for each account set up in Spotcast. 

Essentially I have my own custom lovelace "media" (streaming radio, Spotify etc) launcher card that integrates Spotify using Spotcast and I'd like to get the account playlists to populate using the Spotify account data instead of a manually updated list.

Clear as mud?  lol

Thanks again for having a look at this.  I have a feeling this is kind of a big ask.  I did start putzing around with Python but unfortunately I'm a long way off from being much of a help on that end here.  If there is anything else I can do to help please let me know.

**Comment by jazzyisj** [comment]
Hmm.   This seems like it would be a prime candidate for [the new select entity mentioned in the latest HA Release Notes ](https://www.home-assistant.io/blog/2021/07/07/release-20217/#new-entity-select).  Looks like it could totally eliminate the requirement for automation above that populates the playlist input_select entity.  Might useful for the cast device sources too.

**Comment by jazzyisj** [comment]
Ah ha.  Thought you'd slide this in there without telling anyone eh?  Works perfectly! :-)

Here are my updated automations to populate the input_select and then keep it in sync if the current playing playlist changes via some other method (Spotcast Card, Google Home, Mobile App etc.)

```
- id: spotify_playlist_update_hassio
  alias: "[Spotify] Playlist Update Hassio"
  description: Update spotify playlist input.
  mode: restart
  trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: sensor.playlists_sensor
      attribute: playlists
  condition: "{{ state_attr('sensor.playlists_sensor','playlists')|lower not in ['unknown','unavailable','none'] }}"
  action:
    - service: input_select.set_options
      target:
        entity_id: input_select.spotify_playlist_hassio
      data:
        options: >
          [{% for item in state_attr('sensor.playlists_sensor','playlists') -%}
            "{{- item.name }}"{{ ',' if not loop.last -}}{% endfor %}]

- id: spotify_playlist_selection_update_hassio
  alias: "[Spotify] Playlist Selection Update Hassio"
  description: Update spotify playlist input.
  mode: restart
  trigger:
    - platform: state
      entity_id: media_player.spotify_hassio
      attribute: media_playlist
  condition: "{{ state_attr('media_player.spotify_hassio','media_playlist')|lower not in ['unknown','unavailable','none'] }}"
  action:
    - service: input_select.select_option
      target:
        entity_id: input_select.spotify_playlist_hassio
      data:
        option: "{{ state_attr('media_player.spotify_hassio','media_playlist') }}"
```
And here is how I start Spotcast using the input_select and the playlist sensor URI.

```
- service: spotcast.start
  data:
    device_name: Dining Room Display
    uri: >
      {% for item in state_attr('sensor.playlists_sensor','playlists') -%}
        {% if item.name == states('input_select.spotify_playlist_hassio') %}
          {{ item.uri }}
        {% endif %}
      {% endfor %}
    force_playback: true
```
![image](https://user-images.githubusercontent.com/44064559/131770995-245fd5f4-1bec-4054-b042-bb3bad9af807.png)

Thank you very, very much for taking the time to do this.   The Spotify playlists in my custom media launcher now stay up to date automatically and all those ugly templates are gone!  I think we can consider this mission accomplished!  I do have a couple of suggestions/requests but I'll open separate issues for them.
