### ISSUE TITLE
 'NoneType' object has no attribute 'get' using multiple accounts

### ISSUE THREAD

**Issue by polds** [fondberg/spotcast#168]
I'm running spotcast v3.4.6  and am trying to use multiple accounts. When I try to make a call using one of the configured accounts I see the error ` 'NoneType' object has no attribute 'get'`. My config looks like this:

```yaml
spotcast:
  sp_dc: !secret primary_sp_dc
  sp_key: !secret primary_sp_key
  accounts:
    secondary:
      sp_dc: !secret secondary_sp_dc
      sp_key: !secret secondary_sp_key
```

The request works if I _don't_ include `account: secondary` and fallsback to the primary, but trying to pass in the account yields that error. Any idea what I could have done wrong?
