### ISSUE TITLE
New fields are now mandatory?

### ISSUE THREAD

**Issue by jokerigno** [fondberg/spotcast#197]
Hi,

I used this service call before the update:

```
service: spotcast.start
data:
  entity_id: media_player.corridoio
  uri: 'spotify:track:3YBZIN3rekqsKxbJc9FZko'
```

Now I can't call the service from dev tools anymore.

I had to add at lest thos in order to play music again.

```
service: spotcast.start
data:
  entity_id: media_player.corridoio
  uri: 'spotify:track:3YBZIN3rekqsKxbJc9FZko'
  force_playback: true
  random_song: true
  repeat: track
  offset: 1
```

It' a choice you made for some reason or a bug?
