### ISSUE TITLE
Device not found but it shows up in Spotify card

### ISSUE THREAD

**Issue by gabosom** [fondberg/spotcast#199]
I'm trying start a playlist on my device called "Pioneer Receiver" but I get errors when using the spotcast service. For reference, you can see in the spotify card (end of post) that my HA can actually see the device and I can start playback from this card.

This is the YAML code I have in my script that is not working:

```
service: spotcast.start
data:
  device_name: Pioneer Receiver
  uri: 'spotify:playlist:5tEosAM9zwoygzM5oF8L5z'
  random_song: true
  shuffle: true
```

and I get the below error
```
Logger: homeassistant.components.script.play_spotify_playlist_on_receiver
Source: helpers/script.py:1310
Integration: Script (documentation, issues)
First occurred: April 22, 2021, 4:42:46 PM (2 occurrences)
Last logged: April 22, 2021, 4:44:16 PM

Play Spotify Playlist on Receiver: Error executing script. Error for call_service at pos 2: Could not find device with name Pioneer Receiver 
```

thoughts on what it might be?

![image](https://user-images.githubusercontent.com/926425/115839081-263cab00-a3cf-11eb-84ae-a0832cdbe403.png)
