### ISSUE TITLE
Repeat Context doesn't seem to work

### ISSUE THREAD

**Issue by MrSuttonmann** [fondberg/spotcast#201]
I've been trying this out to play a spotify playlist on repeat.

Repeat Context doesn't seem to be working. The playlist plays, but then stops at the end.

Here's my card config for a button to call the service:

```yaml
type: vertical-stack
cards:
  - type: media-control
    entity: media_player.living_room_speaker
  - type: media-control
    entity: media_player.kitchen_speaker
  - type: vertical-stack
    cards:
      - type: media-control
        entity: media_player.nursery_speaker
      - type: button
        tap_action:
          action: call-service
          service: spotcast.start
          service_data:
            repeat: context
            entity_id: media_player.nursery_speaker
            uri: 'spotify:playlist:REDACTED'
            start_volume: 25
          target: {}
        name: Play Bedtime
        icon: 'hass:music'
        show_icon: false
        show_state: false
        show_name: true
```
