### ISSUE TITLE
Don't have 'get_spotify_devices ' in log after enabing debug log

### ISSUE THREAD

**Issue by fun4stuff** [fondberg/spotcast#235]
**Describe the bug**

* [ ] Using latest version of spotcast
* [ ] I have setup the Spotify integration in Home Assistant
* [ ] I am using multiple accounts
* [ ] Using latest stable version of Home Assistant
* [ ] I have Spotify Premium
* [ ] I'm attaching relevant logs with level debug for component spotcast (see README)
* [ ] I'm using entity_id in the service call and have tried device_name but the issue remains

**Describe the bug**
Don't have 'get_spotify_devices ' in log after enabing debug log

**Environment (please complete the following information):**
 - HA version: [latest ]
 - spotcast version: [latest ]

**Configuration**
logger:
  default: info
  logs:
    custom_components.spotcast: debug

**Additional context**

**Comment by atlflyer** [comment]
Same here. Spotify Premium; latest versions of everything; Spotify Connect device is a RPi on the same network as HA.

```yaml
logger:
  default: warning
  logs:
    homeassistant.components.shell_command: debug
    homeassistant.components.cloud: debug
    homeassistant.cloud: debug
    custom_components.spotcast: debug

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret
  
spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key
```
