### ISSUE TITLE
Error loading /config/configuration.yaml: Secret AQCnU1anJxnU9ghap***********************gNYeq3DM6Gqm0qPsruYlvNwgmRGW7ZXV5Fs49kue3vOnJNFzaTBYxJnQ177fd0eH*********** not defined

### ISSUE THREAD

**Issue by Vince3009** [fondberg/spotcast#268]
I'm facing this issue while testing the configuration? Not sure from what it come. 

Error loading /config/configuration.yaml: Secret AQCnU1anJxnU9ghap***********************gNYeq3DM6Gqm0qPsruYlvNwgmRGW7ZXV5Fs49kue3vOnJNFzaTBYxJnQ177fd0eH********************* not defined

It seems that the configuration is ok : 

spotcast:
  sp_dc: !secret AQCnU1anJxnU9ghap*************************gNYeq3DM6Gqm0qPsruYlvNwgmRGW7ZXV5Fs49kue3vOnJNFzaTBYxJnQ177fd0eH*******************
  sp_key: !secret ae96d4d****************97d4afced5

Both SP_DC and SP_KEY has been taken from Google Chrome with a copy/paste

**Comment by hmmbob** [comment]
Yeah, you're doing this wrong.

In the configuration.yaml, you need to define the 'name' of the secret to use, and the actual secret belongs in secrets.yaml. Example with the data provided:

```yaml
# In configuration.yaml
spotcast:
  sp_dc: !secret spotcast_sp_dc
  sp_key: !secret spotcast_sp_key


# in secrets.yaml
spotcast_sp_dc: AQCnU1anJxnU9ghapgNYeq3DM6Gqm0qPsruYlvNwgmRGW7ZXV5Fs49kue3vOnJNFzaTBYxJnQ177fd0eH
spotcast_sp_key: ae96d4d**********97d4afced5
```

**Comment by Vince3009** [comment]
First of all, thanks a lot for the job done and the quick answer. 

I'm beginning with HA and trying to get the maximum of it but to be honest it starting to be hard for my level but I don't want to give up!

I could do everything properly in sercret.yaml and configuration.yaml (I guess), I could enable the debug logs, I reboot Home Assistant, and went to Configuration >> Logs >> Load Full Home Assistant Log. But **I can not find the log entry** get_spotify_devices and look for the device ID. I've been trying to look for the device ID everywhere but don't get it

**Comment by hmmbob** [comment]
I'm not sure if that is still accurate, but I actually don't use it. Just pass a `media_player` entity to your automation and it should work. Actual example from one of my scripts:

```yaml
    - service: spotcast.start
      data:
        account: t
        entity_id: media_player.slaapkamer
        uri: spotify:track:5OoSxUZSbP1p7kb1d0SozG
```
