### ISSUE TITLE
Unable to start SpotCast - No module named 'spotify_token'

### ISSUE THREAD

**Issue by putz612** [fondberg/spotcast#278]
I am unable to get spotcast to startup, looking in the home assistant logs the only thing I am seeing is this below

2021-12-19 14:15:35 ERROR (MainThread) [homeassistant.config] Package spotify setup failed. Integration spotcast No module named 'spotify_token' (See /config/packages/spotify.yaml:0).

The Spotify integration seems to be working just fine, I am able to control Spotify using Home Assistant, play pause etc.

* [x] Using latest version of spotcast
* [x] I have setup the Spotify integration in Home Assistant
* [ ] I am using multiple accounts
* [x] Using latest stable version of Home Assistant
* [x] I have Spotify Premium
* [x] I'm attaching relevant logs with level debug for component spotcast (see README)
* [ ] I'm using entity_id in the service call and have tried device_name but the issue remains

**Environment (please complete the following information):**
 - HA version: [ 2021.12.3 ]
 - spotcast version: [ v3.6.23 ]

**Configuration**
spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key

spotify:
  client_id: !secret sp_id
  client_secret: !secret sp_secret

**Comment by hmmbob** [comment]
You'll need two spaces in front of `sp_dc`, `sp_key`

**Comment by Darkfull-Dante** [comment]
@putz612 can you provid a debug log of spotcast, we might see what's breaking when home assistant tries to setup the component.

I would also make sure that your configuration respect yaml indentation. It is crucial, yaml can't work without a 2 whitespace indent all the time. It should look like this:

```yaml
# obvioulsy if you do not have multiple accounts you won't have the accounts portion

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_secret

spotcast:
  sp_dc: !secret felix_sp_dc
  sp_key: !secret felix_sp_key
  accounts:
    felix:
      sp_dc: !secret felix_sp_dc
      sp_key: !secret felix_sp_key
    mellissa:
      sp_dc: !secret mellissa_sp_dc
      sp_key: !secret mellissa_sp_key
```

Also, your secret file should lokk like (obvious false data for obvious reasons)
```yaml
# Spotify
felix_sp_dc: asdgfjnmefsgawefgkjn234587324t98hvjdkwfnvqi34htu93rgvnklqerljnv
felix_sp_key: asdfasjdn-vjkqnwerj-klgqbnerj-kgbnq34t

mellissa_sp_dc: asdgnwqekmlrt1q340t9ergn2o34itu130495u13894u513894urt13984t
mellissa_sp_key: 234j5h23kjl4-5h23jk4h523jk452jk345h-2j3k45h2jk34h5c

spotify_client_id: dsjfmghwekljth2314ioj51h34i5
spotify_secret: asdlfjkhqwlekjrh123klj5h1klj
```

@hmmbob i think I will add an install type question in the environnement section of the issue template, might help for future issues to not always have to ask the user

**Comment by putz612** [comment]
Sorry the indents didn't copy and paste across, there are spaces in front, see below.  It does pass the config check internal tester.  I have followed the guides in the readme to enable the debug logs and that is all I see in the logs.  I will bump up the home assistant logs to debug and see if there is anything coming from HA itself.

spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key

spotify:
  client_id: !secret sp_id
  client_secret: !secret sp_secret

**Comment by Darkfull-Dante** [comment]
@putz612, can you show me what the logger part of your configuration file looks like?

**Comment by putz612** [comment]
Absolutely, here is my logger.yaml file, now with indents! Code blocks help
```
logger:
  default: info
  logs:
    custom_components.spotcast: debug
```
Cranking up tp debug for the default logger didn't give me any more details, here is the surronding messages.
```
2021-12-20 12:49:56 WARNING (SyncWorker_6) [homeassistant.loader] We found a custom integration spotcast which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-12-20 12:49:56 WARNING (SyncWorker_8) [homeassistant.loader] We found a custom integration myicomfort which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-12-20 12:50:21 ERROR (MainThread) [homeassistant.config] Package spotify setup failed. Integration spotcast No module named 'spotify_token' (See /config/packages/spotify.yaml:0).
2021-12-20 12:50:21 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event service_registered[L]: domain=logger, service=set_default_level>
2021-12-20 12:50:21 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event service_registered[L]: domain=logger, service=set_level>
2021-12-20 12:50:21 INFO (MainThread) [homeassistant.setup] Setup of domain logger took 0.0 seconds
```
Weird thing is when I look out on the filesystem I do see there is a  deps/lib/python3.9/site-packages/spotify_token.py  and accompanying folders.

**Comment by hmmbob** [comment]
🤔 Weird.

What platform are you running HA on? Anything exotic?

**Comment by Darkfull-Dante** [comment]
The issue is really strange. Normally, without even a debug log, you should have (the following lines, not back-to-back and fairly sparsed depending on your setup):

```yaml
2021-12-20 09:03:23 INFO (MainThread) [homeassistant.setup] Setting up spotify
2021-12-20 09:03:23 INFO (MainThread) [homeassistant.setup] Setup of domain spotify took 0.0 seconds
[...]
# i might have to lines, because I have 2 spotify accounts setup
2021-12-20 09:03:25 INFO (MainThread) [homeassistant.components.media_player] Setting up media_player.spotify
2021-12-20 09:03:25 INFO (MainThread) [homeassistant.components.media_player] Setting up media_player.spotify
```

With the debug log, you should at least have this line:
```yaml
2021-12-20 09:03:26 DEBUG (SyncWorker_7) [custom_components.spotcast.helpers] spotify integration found
```

What I find interesting is the line

```yaml
[...]Package spotify setup failed. Integration spotcast No module named 'spotify_token' (See /config/packages/spotify.yaml:0).
```

There seems to be a yaml file that the configuration is trying to ready, but fails to. Can you verify in your file system if you have such a file and what is the content, also, can you verify if you refer to this file in your configuration.yaml?

**Comment by hmmbob** [comment]
Could you try upgrading to 2021.12.4 and see if that perhaps magically solves the issue?

Chances are slim, but worth a try.

**Comment by cerebrate** [comment]
I have this same issue and have had for the last several versions (all the 2012.12.x releases). No number of HA restarts or component reinstalls have solved the issue.

As above, I have a `/deps/lib/python3.9/site-packages/spotify_token.py`, which does contain the appropriate python code, so the module does appear to be installed. I can confirm that it's the correct module, because a quick hack-test by copying it to the `custom_components/spotcast` folder and modifying `spotcast_controller.py` to load it from there (i.e., `from . import spotify_token as st`) makes the integration work properly. It just doesn't seem to be finding it in deps.

I am running Home Assistant containerized on my k3s cluster.

**Comment by Darkfull-Dante** [comment]
@cerebrate, that looks to me like a permission problem. Might be wrong, but would be useful to check out. Could you send me the content of the spotify_token.py file and also its permission set? If you need guidance, I'll be glad to help.

**Comment by cerebrate** [comment]
@Darkfull-Dante Sure. Here's the content:

```
"""Utility module that helps get a webplayer access token"""
import os
import requests
from bs4 import BeautifulSoup
import json

USER_AGENT = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) \
AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36"

def start_session(dc=None, key=None):
    """ Starts session to get access token. """

    session = requests.Session()

    cookies = {'sp_dc': dc, 'sp_key': key}
    headers = {'user-agent': USER_AGENT}

    response = session.get("https://open.spotify.com/get_access_token?reason=transport&productType=web_player",
                           headers=headers, cookies=cookies)
    response.raise_for_status()
    data = response.content.decode("utf-8")
    config = json.loads(data)

    access_token = config['accessToken']
    expires_timestamp = config['accessTokenExpirationTimestampMs']
    expiration_date = int(expires_timestamp) // 1000
    return access_token, expiration_date%
```

and the permissions are as follows:

```
-rw-rw---- 1 swarm users  957 Oct  9 11:54 spotify_token.py
```

(In case it's relevant, the Home Assistant config volume is an NFS mount, with the recorder database stored elsewhere.)

**Comment by Darkfull-Dante** [comment]
Ok there might be a problem, I see that the file is owned by swarn:users and that the file has no read permissions for others.

Could you try adding read permissions to the file and see if it resolves the issue?

**Comment by Darkfull-Dante** [comment]
Ok there might be a problem, I see that the file is owned by swarn:users and that the file has no read permissions for others.

Could you try adding read permissions to the file and see if it resolves the issue?

**Comment by putz612** [comment]
Sorry I have not had time to update this one, just like @cerebrate I am running on kubernetes using the k8s-at-home helm chart.  To answer @hmmbob upgrading to 2021.12.4 or 2021.12.5 did not change the behavior.  For me here is the contents of spotify_token.py 
```
bash-5.1# cat spotify_token.py 
"""Utility module that helps get a webplayer access token"""
import os
import requests
from bs4 import BeautifulSoup
import json

USER_AGENT = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) \
AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36"

def start_session(dc=None, key=None):
    """ Starts session to get access token. """

    session = requests.Session()

    cookies = {'sp_dc': dc, 'sp_key': key}
    headers = {'user-agent': USER_AGENT}

    response = session.get("https://open.spotify.com/get_access_token?reason=transport&productType=web_player",
                           headers=headers, cookies=cookies)
    response.raise_for_status()
    data = response.content.decode("utf-8")
    config = json.loads(data)

    access_token = config['accessToken']
    expires_timestamp = config['accessTokenExpirationTimestampMs']
    expiration_date = int(expires_timestamp) // 1000
    return access_token, expiration_date
```
And the file permissions
```
bash-5.1# ls -l spotify_token.py 
-rw-r--r--    1 root     root           957 Dec 10 17:31 spotify_token.py
bash-5.1
```

**Comment by Darkfull-Dante** [comment]
At least we have a common point. The problem seems to be caused by the installation type (Kubernetes). @cerebrate @putz612, I have a few questions that might help us go through the problem:

- the permission information that you shown me, was it from the bare metal server or the kubernete pods directly? If it wasn't from inside the pod, can you verify the information from inside the pod?
- Which user is running the pod? Is it root or another user
- From inside the pod what does `whoami` and `groups` return?

**Comment by cerebrate** [comment]
@Darkfull-Dante Mine was from my management box accessing the same NFS share. From inside the pod, the permissions show as:

```
-rw-rw----    1 1004     users          957 Oct  9 16:54 spotify_token.py
```

(These are the same permissions: outside the pod, the uid of _swarm_ is 1004.)

Inside the pod, `whoami` returns `root` and `groups` returns:

```
root bin daemon sys adm disk wheel floppy dialout tape video
```

and the `spotify_token.py` file appears to be readable/writable without other errors.

The pod itself is running with the default (root) security context.

**Comment by Darkfull-Dante** [comment]
ok perfect thank you for the information. I'll investigate the Kubernetes build and see if something in the current Spotcast setup might interfere with access to the deps folder. If all fails, I might look into scrapping the dependency and build an equivalent method for our use case.

**Comment by putz612** [comment]
Here is my info for completeness, all commands were run from within the pod

```
bash-5.1# ls -l deps/lib/python3.9/site-packages/spotify_token.py 
-rw-r--r--    1 root     root           957 Dec 10 17:31 deps/lib/python3.9/site-packages/spotify_token.py
bash-5.1# whoami
root
bash-5.1# groups
root bin daemon sys adm disk wheel floppy dialout tape video
bash-5.1# 
```

**Comment by fcusson** [comment]
@cerebrate , @putz612, After looking into the issue, I have to comme to the conclusion, that the problem reside in the dependency resolvement of the k8s-at-home home assistant implementation. I would suggest you raise the issue with them. This project doesn't have the ability to modify file access in its hosts so any issue of the sort would have to be resolved with the host project.

**Comment by cerebrate** [comment]
FWIW, I'm not actually using the k8s-at-home chart or any other parts of that implementation; I rolled my own simple YAML:

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: homeassistant
  name: homeassistant
  namespace: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      volumes:
        - name: ha-storage
          nfs:
            server: mnemosyne.arkane-systems.lan
            path: "/swarm/harmony/homeassistant/ha"
      containers:
        - image: homeassistant/home-assistant:2021.12.10
          name: home-assistant
          volumeMounts:
            - mountPath: "/config"
              name: ha-storage
```
