### ISSUE TITLE
How do I call an album?

### ISSUE THREAD

**Issue by Stooovie** [fondberg/spotcast#283]
Hi, sorry if this is not the correct place to ask but I don't see any other support site. 

How do I call a specific album instead of a playlist? I use the Mini Media Card which uses Spotcast data model. When I define a playlist with like `id: spotify:user:<me>:playlist:136hsDqjTbnGG4M8qOHREF`
it works but it doesn't call albums. I tried `id: spotify:user:<me>:album:21jF5jlMtzo94wbxmJ18aa`
(Adele's 30) but that doesn't work and usually boots me out of Spotify with `[spotipy.client] HTTP Error for PUT to https://api.spotify.com/v1/me/player/play with Params: {} returned 403 due to Player command failed: Restriction violated`

Thanks.

**Comment by hmmbob** [comment]
`spotify:album:21jF5jlMtzo94wbxmJ18aa` should work

**Comment by Stooovie** [comment]
Ah, it works. Maybe it would be worth it to add this to the documentation, it's not exactly self-evident. Thank you!

**Comment by Darkfull-Dante** [comment]
Regarding the context of this issue, we are working on a validation method for the uri provided. We could add information to the documentation, but I wouldn't go further than providing a link to Spotify's documentation.

If you are not sure about the structure of a URI, I would suggest that you simply copy it from the pc app or browser player by holding `ctrl` while doing in the menu of the relevant element:
![URI copy exemple](https://i.imgur.com/niBbkNz.png)

For the second issue, do you have any error log when trying to use the random song? We did have an issue recently, but it was due to a wrongly typed URI in that case. If you don't have any errors (it simply starts at the top), we might need a debug log to check further.

**Comment by Darkfull-Dante** [comment]
To further document the second issue, I just did the following tests:

# yaml request:
```yaml
service: spotcast.start
data:
  entity_id: media_player.bureau
  uri: <varies per test>
  random_song: true
  shuffle: true
```

| Test | Run count | Result | Passed |
|---|:-:|---|:-:|
| Attempt to play an album | 3 | Random start song, shuffle is on | X |
| Attempt to play a private playlist | 3 | Random start song, shuffle is on | X |
| Attempt to play a public playlist | 3 | Random start song, shuffle is on | X |

**Comment by Stooovie** [comment]
I'm not even able to start music playback through the Services menu.
This:
`service: spotcast.start
data:
  entity_id: media_player.echo_show
  uri: https://open.spotify.com/album/3f22Ap0VSZYWsqrGcphUnY?si=e56a14ce4686411e
  random_song: true
  shuffle: true`
returns this:
`2021-12-22 10:22:45 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Error for call_service at pos 1: Could not find device with name Echo Show
2021-12-22 10:22:45 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [2932013448] Error handling message: Could not find device with name Echo Show`

I can play to these media_player entities fine, just not from Spotcast.

**Comment by Stooovie** [comment]
I'm ultimately trying to have the HA [Mini Media Player card](https://github.com/kalkih/mini-media-player) with a couple of buttons for direct playback of playlists and albums. That works. What doesn't work is seemingly any way of having random playback (shuffle).

This is the entire lovelace card config:
`entity: media_player.spotify_jiri_fiala
type: custom:mini-media-player
source: icon
hide:
  volume: false
shortcuts:
  columns: 4
  buttons:
    - name: Lunchtime
      type: playlist
      id: spotify:user:stooovie:playlist:136hsDqjTbnGG4M8qOHREF
      random_song: true
      shuffle: true
    - name: Vánoce
      type: playlist
      id: spotify:user:stooovie:playlist:1xHgyVvDauxBq8igsliipn
      random_song: true
      shuffle: true
    - name: Xmas Classics
      type: album
      id: spotify:album:3f22Ap0VSZYWsqrGcphUnY
      random_song: true
      shuffle: true
artwork: material
toggle_power: false
`
All those buttons always start on the first track.

**Comment by Darkfull-Dante** [comment]
@Stooovie, please use the recommanded way we provided to get URI. In your first post,you provid a URL, not a URI
> entity_id: media_player.echo_show
> uri: https://open.spotify.com/album/3f22Ap0VSZYWsqrGcphUnY?si=e56a14ce4686411e
> random_song: true

This will not work, you must provide a URI. In the above case `spotify:album:3f22Ap0VSZYWsqrGcphUnY` would be valid

In the second post, you still use `spotify:user:stooovie:playlist:136hsDqjTbnGG4M8qOHREF` which we explain is not a valid URI for Spotcast, you must provid a sharable URI which doesn't go in your surespace, but directly to the playlists pace. A sharable URI should always look like `Spotify:<domain>:<UID>`. You're a telling the Spotify to go to the user space, find the user `stoovie`, oh wait, Spotcast doesn't have the credential for that, abort. It might still be able to play the playlist, but certain functionality in the code is simply not able to handle the unconventional 

Can we make sure that the service works from the dev tools first before going further? Would you be able to test the following service calls:

```
service: spotcast.start
data:
  entity_id: <use a known functionnal media_plyaer>
  random_song: true
  uri: spotify:playlist:136hsDqjTbnGG4M8qOHREF
  shuffle: true
```

```
service: spotcast.start
data:
  entity_id: <use a known functionnal media_plyaer>
  random_song: true
  uri: spotify:playlist:1xHgyVvDauxBq8igsliipn
  shuffle: true
```

```
service: spotcast.start
data:
  entity_id: <use a known functionnal media_plyaer>
  random_song: true
  uri: spotify:album:3f22Ap0VSZYWsqrGcphUnY
  shuffle: true
```

Please make sure to run multiple times to make sure you get a different start song each time. If it still doesn't work, check if you get any error logs and add them to this issue.

**Comment by Darkfull-Dante** [comment]
@Stooovie Additional information, you are not using Mini Media Player card correctly. Their documentation states that `type: playlist` calls the Spotify integration, not Spotcast. Please read their [documentation](https://github.com/kalkih/mini-media-player#card-with-media-shortcuts). They do explain that:

> Tip: If you don't have Sonos, but want just a bit more control over playlists and so, a simple solution is to use the type: service-option, to trigger thespotcast.start-service.
>
> Remember to add the required data, for Spotcast to work. Also, kindly note that the Spotcast custom component is required for this to work. It's available in HACS.

If you are not sure in the correct syntax to call our service from the card, you should open an issue with them, they will be far more knowledgeable for resolving your issue.

They even provide an exemple in their documentation:

```yaml
# Trigger custom service
      - name: Crooners Playlist
        type: service
        id: spotcast.start
        data:
          entity_id: media_player.googlehome1234
          uri: spotify:playlist:37i9dQZF1DX9XiAcF7t1s5
```
