### ISSUE TITLE
Could not get spotify token

### ISSUE THREAD

**Issue by flouck** [fondberg/spotcast#284]
**Describe the bug**
Impossible to get it work. Please see my log.
```
Logger: homeassistant.components.automation.tags_jukebox_playlist
Source: helpers/script.py:1382
Integration: Automatisation (documentation, issues)
First occurred: 19:31:52 (1 occurrences)
Last logged: 19:31:52

Tags - Jukebox playlist: Error executing script. Error for call_service at pos 2: Could not get spotify token
```
And :

```
Logger: homeassistant.components.automation.tags_jukebox_playlist
Source: components/automation/__init__.py:512
Integration: Automatisation (documentation, issues)
First occurred: 19:31:52 (2 occurrences)
Last logged: 19:39:08

Error while executing automation automation.tags_jukebox_playlist: Could not get spotify token
```

**Environment (please complete the following information):**
 - Installation type: [ Home Assistant OS 7.1 ]
 - HA version: [ core-2021.12.7 ]
 - spotcast version: [ v3.6.23 ]

**Configuration**
```
spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret
spotcast:
  sp_dc: !secret spotify_cookie_sp_dc_mathieu
  sp_key: !secret spotify_cookie_sp_key_mathieu
```

And in the automation:
```
  action:
    - variables:
        media_content_id: "{{ tags[trigger.event.data.tag_id].media_content_id }}"
    - service: spotcast.start
      data:
        entity_id: media_player.enceinte
        uri: "{{ media_content_id }}"
        random_song: true
        repeat: true
        shuffle: true
```

**Additional context**
It was working quite some time before. Don't know what happened.
