### ISSUE TITLE
Spotify connect device with 2 accounts not working for 1 account

### ISSUE THREAD

**Issue by mike3190** [fondberg/spotcast#286]
Hi all,

I have 2 accounts working with core spotify and spotcast, in my dashboard I have 2 cards for both accounts where I can select the playlist to start. However it seems only 1 account can choose a spotify connect device at any time. 

I tested this with the smartphone app by playing a song and select the spotify connect device. The latest account connected via this way would be the one that can start a playlist on that spotify connect device via Spotcast.

Is there any way that both accounts can start playback on the same spotify connect device?

Im running HA core-2021.12.7 and Spotcast v3.6.23 (latest)

**Comment by Darkfull-Dante** [comment]
Hi @mike3190, it should be working without problem. Could you provide a copy of your current config file?

A two account setup should look something like this:

```yaml
spotcast:
  sp_dc: !secret felix_sp_dc
  sp_key: !secret felix_sp_key
  country: CA
  accounts:
    felix:
      sp_dc: !secret felix_sp_dc
      sp_key: !secret felix_sp_key
    mellissa:
      sp_dc: !secret mellissa_sp_dc
      sp_key: !secret mellissa_sp_key
```

**Comment by Darkfull-Dante** [comment]
@mike3190

uhm... that's a strange behavior. I can confirm I have it working on my side with two accounts. Device can be found without problem. First and foremost, can you confirm that playback is possible when calling spotcast.start for the two accounts?

Try if possible with restricted content like a private playlist for both. That way we can be sure the call is made to the right account each time. If it works, the problem might be in the way the frontend element makes the playlist and device call.

What I also see is that the account switch seems to gray-out the playlist too which shouldn't happen. The sensor seems to be completly broken for the secondary account.

**Comment by hmmbob** [comment]
There are actually "three" accounts being setup now, two of them being Roos' account. Try this?

```yaml
spotcast:
  sp_dc: !secret roos_sp_dc
  sp_key: !secret roos_sp_key
  accounts:
    mike:
      sp_dc: !secret mike_sp_dc
      sp_key: !secret mike_sp_key
```

Dunno if it fixes stuff, but worth a try
