### ISSUE TITLE
Playlist family users is stuck at loading

### ISSUE THREAD

**Issue by weemaba999** [fondberg/spotcast#296]
**Describe the bug**

* [x] Using latest version of spotcast
* [x] I have setup the Spotify integration in Home Assistant
* [x] I am using multiple accounts
* [x] Using latest stable version of Home Assistant
* [x] I have Spotify Premium
* [x] I'm attaching relevant logs with level debug for component spotcast (see README)
* [x] I'm using entity_id in the service call and have tried device_name but the issue remains

**Describe the bug**

I was excited to read your post on the 'multi-user' approach on spotcast :-) I've been trying whole night to get it configured in my dashboard and I succeeded to get the state-switch, the spotcast integration, the grid with my playlists...

EXCEPT: When I select the second family member, the grid keep stuck on 'loading'. I integrated the other member using spotcast and the dc & key fields from spotcast. The other member is part of the family member subscription

Any idea what might be wrong ?

No idea at all

**Environment (please complete the following information):**

 - Installation type: HA_OS
 - HA version: core-2021.12.10
 - spotcast version: v3.6.24

**Configuration**
Add your configuration

```yaml
spotcast:
  sp_dc: secret
  sp_key: secret
  accounts:
    joos:
     sp_dc: secret
     sp_key: secret
    jessie:
     sp_dc: secret
     sp_key: secret
```

page config:

```yaml
    - type: entities
      style: |
        ha-card {
          border-radius: 5px;
          background-color: var(--dwains-theme-primary);
          --paper-slider-knob-color: var(--dwains-theme-names);
          --paper-slider-active-color: var(--dwains-theme-names);
          --paper-slider-knob-start-color: var(--dwains-theme-grey);
          --paper-slider-container-color: var(--dwains-theme-grey);
        }
      entities:
      {% for speakers in (data | fromjson)['speakers'] %}
        - type: 'custom:slider-entity-row'
          entity: {{ speakers.entity }}
          icon: 'mdi:speaker'
        {% if speakers.name %}
          name: {{ speakers.name }}
        {% endif %}
      {% endfor %}
      
    - type: entities
      entities:
          - entity: input_select.spotify_user_selection
            icon: none
            name: ' '
            # style: |-
            #   ha-paper-dropdown-menu {
            #     padding-left: 20%;
            #     padding-right: 2%;
            #     padding-bottom: 3%;
            #     z-index: 1;
            #     margin-top: -4%;
            #   }
          - type: 'custom:state-switch'
            # style: |-
            #   spotify-card {
            #     margin-top: -15%;
            #   }
            entity: input_select.spotify_user_selection
            states:
              Bart:
                type: 'custom:spotify-card'
                display_style: grid
                limit: 8
                device: mediaplayer_keuken
                # known_connect_devices: 
                #  - name: Badkamer
                #   entity_id: media_player.badkamer
                #  - name: Keuken
                #   entity_id: media_player.keuken
                playlist_type: default
                grid_covers_per_row: 4
                account: default
              Joos:
                type: 'custom:spotify-card'
                display_style: grid
                limit: 8
                playlist_type: default
                grid_covers_per_row: 5
                device: mediaplayer_badkamer
                account: joos
                
              Jessie:
                 
                type: 'custom:spotify-card'
                display_style: grid
                limit: 8
                playlist_type: default
                grid_covers_per_row: 5
                device: mediaplayer_badkamer
                account: jessie
```    

**Additional context**
