### ISSUE TITLE
Spotcast dont play

### ISSUE THREAD

**Issue by michaeltryl** [fondberg/spotcast#307]
I have this code

```yaml
service: spotcast.start
data:
  account: tobias
  uri: https://open.spotify.com/playlist/xxxxxxxxxxxxxxxxxxxxxxxxxxxx
  random_song: true
  entity_id: media_player.tobias
```

But it dont play anything om my Google home.
How can that be. It have worked earlier
