### ISSUE TITLE
Cast Spotify to Nest Hub v2

### ISSUE THREAD

**Issue by thomascour** [fondberg/spotcast#308]
Hi, Spotcast is working really good, I love it. 
I have but one problem. When I want to cast a song on my nest hub, I have to open spotify manually on it first. Do you have a way to open spotify on a nest hub so I can spotcast to it ? 

Thanks a lot for your help

**Comment by hmmbob** [comment]
How are you feeling the service?

Just tested the below, works perfectly fine:

```yaml
service: spotcast.start
data:
  entity_id: media_player.woonkamer
  search: Alan walker alone
```

Based on your description, I guess you are trying to use the `device_name` or `spotify device id`, can you try using the entity_id instead?
