### ISSUE TITLE
Spotcast is not working when using cast as custom component

### ISSUE THREAD

**Issue by TheFes** [fondberg/spotcast#324]
# Bug Ticket

## Describe the bug
I really like it when Cast devices never returned to state `off` in HA 2022.2.1 - 2022.2.3. This was reverted in 2022.2.4.
So I tried to run `cast` as custom component, which works fine for the `cast` devices themselves. However, when doing so, the cast devices can no longer be found by Spotcast. The Chromecast sensor does not show any devices. There is no issue concerning Spotcast in the logs, just the info that the devices are updated, with no devices found.

The actual change to not show them as `off` has no effect on this. Even if I just download the `cast` component, put it in custom_components without any changes (besides adding a version number) Spotcast can not find any cast devices.

* [ X ] Using latest version of spotcast
* [ X ] I have setup the Spotify integration in Home Assistant
* [ X ] I am using multiple accounts
* [ X ] Using latest stable version of Home Assistant
* [ X ] I have Spotify Premium
* [ X ] I'm attaching relevant logs with level debug for component spotcast (see README)
* [ X ] I'm using entity_id in the service call and have tried device_name but the issue remains

## Environment

 - Installation type: HA OS
 - HA version: 2022.4.7
 - spotcast version: v3.6.29

## Configuration
```yaml
spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key
  country: NL
  accounts:
    martijn:
      sp_dc: !secret sp_dc_martijn
      sp_key: !secret sp_key_martijn
    marleen:
      sp_dc: !secret sp_dc_marleen
      sp_key: !secret sp_key_marleen
    pepijn:
      sp_dc: !secret sp_dc
      sp_key: !secret sp_key
    floris:
      sp_dc: !secret sp_dc_floris
      sp_key: !secret sp_key_floris
```

## Service Call
N/A

## Additional context
N/A

**Comment by fcusson** [comment]
We cannot guarantee functionality using a custom component. Spotcast requires access to the cast native integration to check the list of devices and communicate with them correctly. If the service calls and the hooks are made differently it will not work.

In your post you talk about providing a log and that the log mentions no device was found. The log is not in the ticket, can you please provide it so we can investigate it. 

Also please provide the link for the custom integration. We will have to test with it has We are not using that integration ourselves.

**Comment by TheFes** [comment]
Thanks for the reply.
There is no custom integration to link to, the custom integration is the existing cast integration
(current version [here](https://github.com/home-assistant/core/tree/2022.4.7/homeassistant/components/cast))

Steps to reproduce:
* Download the latest release source code zip from [this link](https://github.com/home-assistant/core/releases) (for some reason 2022.4.7 is missing here, so I used 2022.4.6)
* Put the /homeassistant/components/cast folder in /config/custom_components/
* edit manifest.json to add a version number
* reboot HA

Changed manifest.json
```json
{
  "domain": "cast",
  "name": "Google Cast",
  "version": "6.6.6",
  "config_flow": true,
  "documentation": "https://www.home-assistant.io/integrations/cast",
  "requirements": ["pychromecast==11.0.0"],
  "after_dependencies": [
    "cloud",
    "http",
    "media_source",
    "plex",
    "tts",
    "zeroconf"
  ],
  "zeroconf": ["_googlecast._tcp.local."],
  "codeowners": ["@emontnemery"],
  "iot_class": "local_polling",
  "loggers": ["casttube", "pychromecast"]
}
```
Now the cast component in the custom_components folder will be used instead of the core version, but no adjustments were made, so it should be completely the same.
Of course this makes no sense to do, what I would want to achieve is to revert this [change](https://github.com/home-assistant/core/pull/66005) but even without making changes to the cast component, spotcast will no longer work.

I also added spotcast to the debug logs before rebooting.

After reboot I see the following in my logs:
```
2022-04-26 14:59:26 DEBUG (SyncWorker_16) [custom_components.spotcast.helpers] spotify integration found
2022-04-26 14:59:26 DEBUG (SyncWorker_19) [custom_components.spotcast.sensor] initiating sensor
2022-04-26 14:59:26 DEBUG (SyncWorker_19) [custom_components.spotcast.sensor] initiating playlist sensor

2022-04-26 15:00:26 DEBUG (SyncWorker_13) [custom_components.spotcast.sensor] Getting chromecast devices
2022-04-26 15:00:26 DEBUG (SyncWorker_13) [custom_components.spotcast.sensor] sensor devices []
2022-04-26 15:00:26 DEBUG (SyncWorker_12) [custom_components.spotcast.sensor] Getting playlists
2022-04-26 15:00:26 DEBUG (SyncWorker_12) [custom_components.spotcast.spotcast_controller] setting up with  account default
2022-04-26 15:00:26 DEBUG (SyncWorker_12) [custom_components.spotcast.spotcast_controller] expires: 1650978562 time: 1650978026.2843597
```
The last 5 lines are repeated every minute. As you can see the sensor devices are an empty list, which is also reflected in the sensor itself:

```yaml
state: 'OK'
devices_json: '[]'
devices: []
last_update: '2022-04-26T15:04:26.608292+02:00'
friendly_name: Chromecast Devices
```

So, there I'm actually using the official core cast component, the only change I made right now is moving it to the custom_components folder and adding a version number.
