### ISSUE TITLE
Error in pychromecast socket - filedescriptor out of range in select()

### ISSUE THREAD

**Issue by alexandernajafi** [fondberg/spotcast#360]
# Bug Ticket

## Describe the bug

Error log `Error in select call: filedescriptor out of range in select()` from spotcast.

I have a script casting Spotify to a Google Home Mini and have defined the device using the entity_id. It used to work but then one day it simply stopped working. 

Service in script:

```
  - service: spotcast.start
    data:
      entity_id: media_player.sovrum_speaker
      uri: spotify:track:1VJRxqJhpEIpnHon7ssp1p
      repeat: track
```

Full error is

```
Logger: pychromecast.socket_client
Source: /usr/local/lib/python3.10/site-packages/pychromecast/socket_client.py:571
First occurred: 7 november 2022 04:35:53 (2669191 occurrences)
Last logged: 19:59:24

[device-name(ip):8009] Error in select call: filedescriptor out of range in select()
[device-name(ip):8009] Error in select call: filedescriptor out of range in select()
[device-name(ip):8009] Error in select call: filedescriptor out of range in select()
[device-name(ip):8009] Error in select call: filedescriptor out of range in select()
[device-name(ip):8009] Error in select call: filedescriptor out of range in select()
```

The error is followed by another error in the logs:

```
Logger: pychromecast.socket_client
Source: /usr/local/lib/python3.10/site-packages/pychromecast/socket_client.py:663
First occurred: 6 november 2022 18:24:39 (2672794 occurrences)
Last logged: 20:05:02

[device-name(ip):8009] Error communicating with socket, resetting connection
[device-name(ip):8009] Error communicating with socket, resetting connection
[device-name(ip):8009] Error communicating with socket, resetting connection
[device-name(ip):8009] Error communicating with socket, resetting connection
[device-name(ip):8009] Error communicating with socket, resetting connection
``` 

* [x] Using latest version of spotcast
* [x] Using latest stable version of Home Assistant
* [x] I have setup the Spotify integration in Home Assistant
* [x] I have Spotify Premium
* [ ] I am using multiple accounts
* [x] I have renewed my `sp_dc` and `sp_key` values and restarted Home Assistant (see README)
* [x] I'm attaching relevant logs with level debug for component spotcast (see README)
* [ ] I'm using entity_id in the service call and have tried device_name but the issue remains

## Environment

 - Installation type: [HA_OS]
 - HA version: [2022.11.1]
 - spotcast version: [3.6.30]

## Configuration

```
spotcast:
  sp_dc: -
  sp_key: -
  country: SE
```

## Service Call

```
  - service: spotcast.start
    data:
      entity_id: media_player.sovrum_speaker
      uri: spotify:track:1VJRxqJhpEIpnHon7ssp1p
      repeat: track
```

## Additional context

-
