### ISSUE TITLE
spotify + spotcast + echoDot

### ISSUE THREAD

**Issue by tof92130** [fondberg/spotcast#361]
# Bug Ticket

Hello,

I don't succeed to find my Echo Dots

## Describe the bug
Error Message :

`Échec d'appel du service spotcast.start. Could not find device with name EchoDot Chambre`

Log error:

```
  File "/config/custom_components/spotcast/spotcast_controller.py", line 62, in __init__
    self.castDevice = self.getChromecastDevice(device_name)
  File "/config/custom_components/spotcast/spotcast_controller.py", line 88, in getChromecastDevice
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Could not find device with name EchoDot Salon
```

* [x ] Using latest version of spotcast
* [x ] Using latest stable version of Home Assistant
* [x ] I have setup the Spotify integration in Home Assistant
* [x ] I have renewed my `sp_dc` and `sp_key` values and restarted Home Assistant (see README)
* [x ] I'm attaching relevant logs with level debug for component spotcast (see README)
* [x ] I'm using entity_id in the service call and have tried device_name but the issue remains

## Environment

 - Installation type: [HA_OS]
 - HA version: [ 2022-01]
 - spotcast version: [last]

## Configuration

RPi4
Echo Dot 3rd Gen

## Service Call

```
type: custom:mini-media-player
entity: media_player.echodot_salon_3
icon: mdi:music
artwork: material
name: Salon
shortcuts:
  columns: 4
  label: Listes
  list:
    - type: custom
      name: Nostalgie
      id: play Nostalgie on tunein
      icon: mdi:radio
    - type: custom
      name: RFM
      id: play RFM on tunein
      icon: mdi:radio
    - type: script
      name: Sud Radio
      id: script.media_play_sud_radio
      icon: mdi:radio
    - type: service
      name: Natasha St Pier
      id: spotcast.start
      data:
        entity_id: media_player.echodot_salon_3
        uri: spotify:playlist:337vWGzwM7Vnf04HDR2lW7
        random_song: true
        shuffle: true
      icon: mdi:music
```
