### ISSUE TITLE
Unable to start spotcast for PS5 during rest mode

### ISSUE THREAD

**Issue by algovera** [fondberg/spotcast#390]
In home assistant, i am able to make ps5 to play song / album / playlist by calling

```
service: spotcast.start
data:
  spotify_device_id: "....."
  uri: "...."
```

However, when PS5 is in rest mode, I am unable to wake it up by the same service call, while I am able to wake it via Mobile or Desktop app by selecting PS5 as a Spotify Connect device.

As soon as PS5 is awake, the same service call works again.

I've tried deleting and creating a new app in Spotify Developer, also a new spotcast sp_dc and sp_key, and they didn't work niehter.

 
Please advise
