### ISSUE TITLE
Artist playback does not start with random song

### ISSUE THREAD

**Issue by Coxeroni** [fondberg/spotcast#392]
Whenever I try to start an artist playback, the very same song always comes first (probably the first in the spotify sequences for that artist) and only after that the songs come in random order.

My yaml for such a playback looks like this:
```
service: spotcast.start
data:
  uri: spotify:artist:5e7w4jeuld5367jaczHkng
  shuffle: true
  repeat: context
  device_name: Gästezimmer
  account: ferdi
  random_song: true
```

Is there any mistake I am making? Random start works fine for playlists and albums as far as I could tell, but not for the artist.

Thanks for the help!
