### ISSUE TITLE
Play 2 Spotify playlists simultaneously on different devices

### ISSUE THREAD

**Issue by messagedj** [fondberg/spotcast#414]
I have a Spotify Premium Family account, and I have set up 3 accounts in HA and they work perfectly. I can play all of them but I can't play them simultaneously on different devices.

**_I want to create an automation where my 2 daughters can listen to their own playlist on they own Google Home Minis._** 

* [x ] Using latest version of spotcast
* [x ] Using latest stable version of Home Assistant
* [x ] I have setup the Spotify integration in Home Assistant
* [x ] I have renewed my `sp_dc` and `sp_key` values and restarted Home Assistant (see [README](https://github.com/fondberg/spotcast#enabling-debug-log))
* [x ] (optional) I have Spotify Premium
* [x ] (optional) I am using multiple accounts

## Configuration
````
spotcast:
  sp_dc: !secret primary_sp_dc
  sp_key: !secret primary_sp_key
  country: NL #optional, added in 3.6.24
  accounts:
    julia:
      sp_dc: !secret julia_sp_dc
      sp_key: !secret julia_sp_key
    liselot:
      sp_dc: !secret liselot_sp_dc
      sp_key: !secret liselot_sp_key `


# Config
<insert configuration here>

alias: Spotify Julia op Julia
sequence:
  - service: media_player.play_media
    target:
      entity_id: media_player.nestmini4851
    data:
      media_content_id: >-
        spotify://XXXXXXXXXXXXX/spotify:playlist:XXXXXXXXXXXXX
      media_content_type: spotify://playlist
    metadata:
      title: "POV: you are happy!!! (2)"
      thumbnail: >-
        https://mosaic.scdn.co/640/a XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
      media_class: playlist
      children_media_class: track
      navigateIds:
        - {}
        - media_content_type: spotify://library
          media_content_id: spotify://XXXXXXXXXXXXX XXXXXXXXXXXXX
        - media_content_type: spotify://current_user_playlists
          media_content_id: spotify://XXXXXXXXXXXXX/current_user_playlists
        - media_content_type: spotify://playlist
          media_content_id: >-
            spotify://XXXXXXXXXXXXX/spotify:playlist: XXXXXXXXXXXXX
  - service: media_player.volume_set
    data:
      volume_level: 0.13
    target:
      device_id: XXXXXXXXXXXXXXXXXXXXXXXXXX
mode: parallel
````

**Comment by mindtripper** [comment]
Can't see that you are using SpotCast in your example YAML above. Looks like you are using HA's built in Spotify integration to play.

Have a look at: https://github.com/fondberg/spotcast#start-playback-on-a-device-with-non-default-account

I have the same use-case as you, but I leverage SpotCast integration `spotcast.start` to cast to ChromeCasts.
See if you can use the examples below in automations created for you kids:

```
- service: spotcast.start
  data:
    entity_id: media_player.nestmini_<julia>
    uri: "spotify:playlist:XXXXXXXXXXXXXXXXXXXXXXXXXX"
    account: "julia"
    # Below is optional
    force_playback: true
    random_song: true
    shuffle: true
    repeat: context
```

```
- service: spotcast.start
  data:
    entity_id: media_player.nestmini_<liselot>
    uri: "spotify:playlist:XXXXXXXXXXXXXXXXXXXXXXXXXX"
    account: "liselot"
    # Below is optional
    force_playback: true
    random_song: true
    shuffle: true
    repeat: context
```
