### ISSUE TITLE
Failed to call service spotcast/start. Could not find device with name media_player.sonos_arc_woonkamer

### ISSUE THREAD

**Issue by NoahvdVen** [fondberg/spotcast#415]
Hi there, 

I was trying to set up spotcast with the mini media player. But once i tried to play a playlist, it gave me the following error:
`Failed to call service spotcast/start. Could not find device with name Arc Woonkamer`

This seems to only be the issue with Sonos devices, since my Nest speakers are working completely fine. Has anything changed?

This is the configuration i'm using:
```
type: custom:mini-media-player
entity: media_player.sonos_arc_woonkamer
artwork: cover
icon: mdi:speaker
name: Muziek woonkamer
hide:
  shuffle: false
  icon_state: false
  power: false
shortcuts:
  columns: 2
  buttons:
    - name: Top 40
      type: service
      id: spotcast.start
      data:
        device_name: Arc Woonkamer
        uri: spotify:playlist:*bleep*
        random_song: true
        shuffle: true
```
