### ISSUE TITLE
device_name empty even after using entity_id

### ISSUE THREAD

**Issue by t-abraham** [fondberg/spotcast#420]
# Bug Ticket

## Describe the bug

The service always looks for device_name even after providing the entity_id. It was working great till yesterday and then after the recent updates of both HA and the spotcast to the latest 3.7.1 something broke. I cant confirm if its HA or spotcast.

## Troubleshooting

Make sure to validate all the elements before submitting the ticket (Exception to the steps marked as optional)

* [x] Using latest version of spotcast
* [x] Using latest stable version of Home Assistant
* [x] I have setup the Spotify integration in Home Assistant
* [x] I have renewed my `sp_dc` and `sp_key` values and restarted Home Assistant (see [README](https://github.com/fondberg/spotcast#enabling-debug-log))
* [x] (optional) I have Spotify Premium
* [x] (optional) I am using multiple accounts
* [x] (optional) I'm attaching relevant logs with level debug for component spotcast (see [README](https://github.com/fondberg/spotcast#enabling-debug-log))
* [x] (optional) I'm using entity_id in the service call and have tried device_name but the issue remains

## Environment

 - Installation type: [HA_OS]
 - HA version: [2024.1.6]
 - spotcast version: [3.7.1]

## Configuration

````yaml
# please remove any sensitive information like cookies and token keys
<insert configuration here>

````

## Service Call

If relevant, provide a `yaml` of the service call or explain the action taken to replicate the issue.

````yaml
service: spotcast.start
data:
  account: home_assistant
  limit: 20
  force_playback: false
  random_song: true
  repeat: true
  shuffle: true
  offset: 0
  ignore_fully_played: false
  uri: spotify:playlist:7KvP5E4IuBi6ctxgA9goAS
  entity_id: media_player.bathroom_speaker
  start_volume: 5
````

## Logs

* normal

````log
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/connection.py:301
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 8:44:19 PM (7 occurrences)
Last logged: 8:57:44 PM

[139814657054400] Error handling message: device_name is empty (home_assistant_error) Tahasanul Ibrahim from xxx.xxx.xxx.xxx (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0)
````

## Additional context

![spotcast](https://github.com/fondberg/spotcast/assets/17075361/aa884b65-79d9-4bfb-86ca-2e7a7ede2372)
