### ISSUE TITLE
Spotcast Could not find spotify media player

### ISSUE THREAD

**Issue by TailScaleRem** [fondberg/spotcast#476]
# Bug Ticket

## Describe the bug
Hi there,
My Spotcast integration stopped working a few days ago. 
When starting spotcast.start the error "Could not find spotify media player" appears.
 I have already re-read and re-entered the keys for Spotcast and created a new app for the Spotify integration.

Does anyone have an idea?

Spotcast is Version 4.0, Home Assistant CORE is 2024.11.2

## Troubleshooting

Make sure to validate all the elements before submitting the ticket (Exception to the steps marked as optional)

* [ X] Using latest version of spotcast
* [X ] Using latest stable version of Home Assistant
* [X ] I have setup the Spotify integration in Home Assistant
* [ X] I have renewed my `sp_dc` and `sp_key` values and restarted Home Assistant (see [README](https://github.com/fondberg/spotcast#enabling-debug-log))
* [ X] (optional) I have Spotify Premium
* [ ] (optional) I am using multiple accounts
* [ ] (optional) I'm attaching relevant logs with level debug for component spotcast (see [README](https://github.com/fondberg/spotcast#enabling-debug-log))
* [ ] (optional) I'm using entity_id in the service call and have tried device_name but the issue remains

## Environment

 - Installation type: [HA_OS]
 - HA version: [ 2024.11.2]
 - spotcast version: [4.0.0 ]

## Configuration

````yaml
# please remove any sensitive information like cookies and token keys
spotcast:
  sp_dc: a lot of 
  sp_key: Not so much 
  country: DE #optional, added in 3.6.24

````

## Service Call

If relevant, provide a `yaml` of the service call or explain the action taken to replicate the issue.

````yaml

'1712941494483':
  alias: Schlafzimmer Google Gute Nacht Geschichten
  sequence:
  - data:
      limit: 20
      force_playback: false
      random_song: false
      repeat: context
      shuffle: false
      offset: 0
      ignore_fully_played: false
      uri: spotify:playlist:4wb2TI6gEi10v9FsoynpF5
      device_name: Schlafzimmer
      start_volume: 17
    action: spotcast.start
````

## Logs

* normal|debug

````log
<please insert any relevent logs here>
````

## Additional context

<Add any other context about the problem here.>
