### ISSUE TITLE
Some time Error: Could not get spotify token.

### ISSUE THREAD

**Issue by MaxAu72** [fondberg/spotcast#492]
### The problem

Hi All,
some time I received the error in the object:
Could not get spotify token.

I created an automation in HA that after it told a message, wait 10 seconds and start spotcast command.
The automation works, but some time I received the error. If I execute the  automation in manual it's ok.

````yaml
Errore: Could not get spotify token.
Risultato:
params:
  domain: spotcast
  service: start
  service_data:
    limit: 20
    force_playback: false
    random_song: false
    repeat: 'off'
    shuffle: false
    offset: 0
    ignore_fully_played: false
    entity_id: media_player.studio
    uri: spotify:playlist:7aOZbJaEjS1ghjPxW1ncCZ
    start_volume: 40
  target: {}
running_script: false
````

### System Health details

Core
2024.11.3
Supervisor
2024.11.4
Operating System
13.2
Frontend
20241106.2

### Spotcast Version

v4.0.0

### What type of installation are you running?

Home Assistant OS

### Anything in the logs that might be useful for us?

````log
Fonte: helpers/script.py:2032
Error executing script. Error for call_service at pos 6: Could not get spotify token.
````

````log
Fonte: components/automation/__init__.py:764
Error while executing automation automation.sveglia_aurora_mattina_7_20: Could not get spotify token.
````
