### ISSUE TITLE
Playing random song

### ISSUE THREAD

**Issue by SchBenedikt** [fondberg/spotcast#507]
### The problem

I have a question: Usually, the songs always have some kind of playlist ID, song ID, etc. But is there a way to just play random songs, for example from all the people I follow?

Thank you in advance!

### System Health details

HomeAssistant OS
core-2025.1.0

### Spotcast Version

v4.0.0

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

-

### Example YAML snippet

```yaml
show_name: true
show_icon: true
type: button
name: start Random Song
tap_action:
  action: call-service
  service: spotcast.start
  service_data:
    device_name: Grundig Media Player
    random_song: true
```
