### ISSUE TITLE
My Spotify media players for Amazon Echo Show devices are multiplying

### ISSUE THREAD

**Issue by Mika255** [fondberg/spotcast#509]
### The problem

Installation of Spotcast 5.0.0-b21 went really smoothly, all good!
I could create my voice automation to start a song.

However, this morning, my "Alexa Show" ("Mikas Echo Koch") created a new media_player with a different id.
Playing back with the old media_player wasn't supported anymore.

Also the Amazon "play on every device" group called "Überall" multiplied itself, see

<img width="1075" alt="image" src="https://github.com/user-attachments/assets/8fa68dfd-df32-4bb0-a83e-44526e4918fd" />

## System Information

version | core-2025.1.1
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.13.1
os_name | Linux
os_version | 4.4.302+
arch | x86_64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 5000
Installed Version | 2.0.2
Stage | running
Available Repositories | 1507
Downloaded Repositories | 50

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | January 30, 2025 at 1:00 AM
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | false
remote_connected | false
alexa_enabled | false
google_enabled | false
cloud_ice_servers_enabled | false
remote_server | eu-central-1-23.ui.nabu.casa
certificate_status | ready
instance_id | 7df51d9db3a340478c56f664ee3acd07
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | null
-- | --
update_channel | stable
supervisor_version | supervisor-2025.01.0.dev0301
agent_version | null
docker_version | 20.10.23
disk_total | 11083.2 GB
disk_used | 4644.8 GB
healthy | true
supported | failed to load: Unsupported
host_connectivity | null
supervisor_connectivity | true
ntp_synchronized | null
virtualization | 
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.16.0), Hass Calendar Addon (0.501), ESPHome Device Builder (2024.12.2), Matter Server (7.0.0), File editor (5.8.0), Piper (1.5.2), Whisper (2.4.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 8
-- | --
resources | 56
views | 47
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | December 5, 2024 at 11:46 PM
-- | --
current_recorder_run | January 8, 2025 at 1:08 AM
estimated_db_size | 1887.79 MiB
database_engine | sqlite
database_version | 3.47.1

</details>

<details><summary>Spotcast</summary>

Version | 5.0.0-b21
-- | --
316ak3cwisv5mvmayhawp24hknxa Is Default | true
316ak3cwisv5mvmayhawp24hknxa Public Endpoint | ok
316ak3cwisv5mvmayhawp24hknxa Public Token | healthy
316ak3cwisv5mvmayhawp24hknxa Private Endpoint | ok
316ak3cwisv5mvmayhawp24hknxa Private Token | healthy
316ak3cwisv5mvmayhawp24hknxa Product | premium

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### What type of installation are you running?

Home Assistant Supervised

### Diagnostics information

I have enabled diagnostics, and will provide some traces tomorrow.

### Example YAML snippet

```yaml
I honestly don't think its related to the voice automation, but here we go:

alias: Voice - Spotify
description: ""
triggers:
  - trigger: conversation
    command:
      - Spiele [Lied|liebt] {song} [auf Spotify]
    id: id_song
    enabled: true
  - trigger: conversation
    command:
      - Spiele Playlist {playlist} [auf Spotify]
      - Spiele {playlist} Playlist [auf Spotify]
    id: id_playlist
    enabled: true
conditions: []
actions:
  - alias: Play Spotify playlist or search for song
    choose:
      - conditions:
          - condition: trigger
            id:
              - id_song
        sequence:
          - action: spotcast.play_from_search
            data:
              media_player:
                entity_id: >-
                  media_player.mikas_echo_koch_316ak3cwisv5mvmayhawp24hknxa_spotcast_2
              item_types:
                - album
                - artist
                - playlist
                - track
              search_term: "{{trigger.slots.song}}"
              data:
                shuffle: true
          - set_conversation_response: Okay, spiele {{trigger.slots.song}}
      - conditions:
          - condition: trigger
            id:
              - id_playlist
        sequence:
          - action: spotcast.play_from_search
            data:
              media_player:
                entity_id: >-
                  media_player.mikas_echo_koch_316ak3cwisv5mvmayhawp24hknxa_spotcast_2
              item_types:
                - playlist
              search_term: "{{trigger.slots.playlist}}"
              data:
                shuffle: true
          - set_conversation_response: Okay, spiele Playlist {{trigger.slots.playlist}}
mode: single
```

### Additional information

from https://api.spotify.com/v1/me/player/devices

```json
{
  "devices": [
    {
      "id": "b6a55ac0-1113-41f7-a55d-2b3c1e1d46bc_amzn_1",
      "is_active": false,
      "is_private_session": false,
      "is_restricted": false,
      "name": "Mikas Echo Eck",
      "type": "Speaker",
      "volume_percent": 29,
      "supports_volume": true 
    },
    {
      "id": "234add95-59e5-4d03-91d0-3af661a2e097_amzn_1",
      "is_active": false,
      "is_private_session": false,
      "is_restricted": false,
      "name": "Mikas Echo Klo",
      "type": "Speaker",
      "volume_percent": 45,
      "supports_volume": false
    },
    {
      "id": "43fd6307-85d7-4d11-93de-3d9bee2696b3_amzn_2",
      "is_active": false,
      "is_private_session": false,
      "is_restricted": false,
      "name": "Überall",
      "type": "Speaker",
      "volume_percent": 40,
      "supports_volume": true
    },
    {
      "id": "43fd6307-85d7-4d11-93de-3d9bee2696b3_amzn_1",
      "is_active": true,
      "is_private_session": false, 
     "is_restricted": false,
      "name": "Mikas Echo Koch",
      "type": "Speaker",
      "volume_percent": 40,
      "supports_volume": true
    }
  ]
}
```
