### ISSUE TITLE
Invalid data for call_service at pos X: value should be a string for dictionary value @ data['entity_id']

### ISSUE THREAD

**Issue by sup3rmark** [fondberg/spotcast#51]
When I try to include a `Call Service` action for the `spotcast.start` service in a HomeAssistant automation (specifying `media_player.upstairs` as the entity_id, which points to a speaker group called `upstairs` and is a functional entity everywhere else), it fails to call the service with the following error:

> Error while executing automation automation.playlist. Invalid data for call_service at pos 1: value should be a string for dictionary value @ data['entity_id']

Making the same exact call from the Developer Tools > Services page works, but there seems to be a problem when doing this as an automation. I'm using the correct Entity ID for the player in question (I've tried with both a speaker group and an individual Google Home device), so that's not the issue.

HA is 0.105.2.

**Comment by fondberg** [comment]
There is nothing a component can do different between all these calls. There must be something wrong in your automation.

**Comment by sup3rmark** [comment]
There's nothing wrong in the automation. It uses the same values as the service call.

Action type: `Call service`
Service: `spotcast.start`
The entity_id of the chromecast mediaplayer (not used together with device_name): `media_player.guest_room_hub`
Service data: `uri: 'spotify:playlist:6q3VQ83mS4EHYFtOMf8Tj5'`

I've also tried including `entity_id: media_player.guest_room_hub` in the Service Data field (in addition to the entity_id field, but get the same error in the HA log: `Error while executing automation automation.music. Invalid data for call_service at pos 1: value should be a string for dictionary value @ data['entity_id']`.

I've tried this in an automation with other steps that execute with no issues, and in an automation with no other steps.

**Comment by fondberg** [comment]
As I wrote, there is no difference for a component between using the service call in the dev UI or using an automation. Hence the problem is NOT in this component.

Beware that automations can have newlines as values for parameters. These need to be stripped before sending service calls

**Comment by sup3rmark** [comment]
Okay. I'll open an issue in the HomeAssistant repo.
In the meantime, as a workaround (which I'll leave here for anyone else who comes across the same problem): specifying the `entity_id` in the GUI was what was causing this problem. You can't save an automation with a blank entity ID in the GUI, but you can save it and then remove the `entity_id` in the YAML directly (it still needs to be listed in the data). It should look like this:

```yaml
- id: 'xxx'
  alias: Playlist
  description: Start the "go-to" playlist from Spotify on the Upstairs speaker group
  trigger:
  - platform: webhook
    webhook_id: music
  condition: []
  action:
  - data:
      entity_id: media_player.upstairs
      random_song: true
      uri: spotify:playlist:6q3VQ83mS4EHYFtOMf8Tj5
    service: spotcast.start
```

**Comment by fondberg** [comment]
entity_id is always a property to data.

**Comment by sup3rmark** [comment]
Sure. The problem, though, is that the GUI was requiring that I fill in the separate entity_id field for the automation as well, and that was causing the automation to fail.

**Comment by crowbarz** [comment]
In the automation and script editors, you can also click the `⋮` to the right of Call service and Edit as YAML directly from the GUI. It will let you save as long as the YAML is valid.

For other services, `entity_id` can be specified at the `action` level as well, one level above `data`, though it seems to 'magically' move at some stage to a property of `data`. For example, my spotcast script calls `media_player.shuffle` with `entity_id` at the `action` level, and that works fine:

```
  sequence:
  - data:
      entity_id: media_player.xxx
      random_song: true
      repeat: 'off'
      uri: spotify:playlist:xxx
    service: spotcast.start
  - data:
      shuffle: true
    entity_id: media_player.xxx
    service: media_player.xxx
```

The error that I get when `entity_id` specified at the action level for `spotcast.start` is a schema validation error:

> voluptuous.error.MultipleInvalid: value should be a string for dictionary value @ data['entity_id']

So it looks like HA is passing some other data type when the service is called and that is causing a schema mismatch. I tried hacking `entity_id` to require a value of type `cv.entity_id` [here](https://github.com/fondberg/spotcast/blob/master/custom_components/spotcast/__init__.py#L36) to match what I have seen done elsewhere, but that didn't seem to solve the issue.
