### ISSUE TITLE
In podcast/show only play one episode

### ISSUE THREAD

**Issue by litecross91** [fondberg/spotcast#516]
### The problem

When I start a podcast with the script below, only the first episode plays and then it stops. This is what version 4.x did. Is there a workaround to keep it going to the next episode? Thanks!
tested show: https://open.spotify.com/show/6vgwu6GE3ACjEFRtckHVSu
Experienced this issue with full URL and with URI.

The current episode starts. When this episode is over, it does not switch to the next one. This is my problem.

```
- action: spotcast.play_media
    data:
      media_player:
        entity_id: media_player.konyha_soundbar
      spotify_uri: spotify:show:6vgwu6GE3ACjEFRtckHVSu
```

### System Health details

Core
2025.2.1
Supervisor
2025.02.0
Operating System
14.2
Frontend
20250205.0

Spotcast version: v5.0.0-b29
Installed from HACS.

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

[home-assistant_spotcast_2025-02-11T14-49-58.350Z.log](https://github.com/user-attachments/files/18751781/home-assistant_spotcast_2025-02-11T14-49-58.350Z.log)

### Example YAML snippet

```yaml

```

### Anything in the logs that might be useful for us?

```txt

```
