### ISSUE TITLE
playback on idle mediaplayer not working

### ISSUE THREAD

**Issue by pipetboy** [fondberg/spotcast#519]
### The problem

In previous versions of Spotcast, I could use force_playback to start spotify on an idle device. How is this done in V5? I'm not seeing it referenced anywhere, and using spotcast.play_liked_songs or spotcast.transfer_playback only starts when the mediaplayer is already active.
When the mediaplayer is idle, I get:
"HomeAssistantError: Timeout when waiting for status response from Spotify app"
(please note: it does work when the mediaplayer is active)

### System Health details

<html><body>
<div class="card-header"><h3>Spotcast</h3>  </div>  
Version | 5.0.0-b29
-- | --
Theo_bijma Is Default | true
Theo_bijma Public Endpoint | ok
Theo_bijma Public Token | healthy
Theo_bijma Private Endpoint | ok
Theo_bijma Private Token | healthy
Theo_bijma Product | premium

</body>
</html>

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

.

### Example YAML snippet

```yaml

```

### Anything in the logs that might be useful for us?

```txt

```

**Comment by fcusson** [comment]
@pipetboy. First there is a misunderstanding about what `force_playback` was doing, it was never to wakeup devices, its to ensure that when you transfer playback if the active playback was inactive (from Spotify point of view, not media player), it will also send the play query to Spotify API. As defined here:

```yaml
force_playback:
      name: "Force Playback"
      description: "In case of transfering playback: If true starts playing the user's last playback even if nothing is currently playing."
      example: true
      required: false
      default: false
      selector:
        boolean:
```

Also, there is a lot of information missing for us to be able to help you. Here are information not original provided in your ticket that we need:

- You mention calling a service and having an error, but do not provide the service call or the relevant error log. 
- I would also need to know the kind of devices you are trying to call. Officially, the only devices that are working with Spotcast are chromecast devices and spotify connect device if they are already registered to the account.
- Optional, but might be required down the lone. A debug logs with more details of your attempt at calling `spotcast.transfer_playback` would be helpful to better undertand what is going on
- The system health information cuts out a lot of relevant information. I understand wanting to remove unnecessary information and thats ok, but please do not remove the `System Information` section as it contains a lot of important information about the current version of Home Assistant you are running.

Please add relevant information as requested, in order for us to help your issue
