### ISSUE TITLE
Casting to the new Home Assistant Voice PE device.

### ISSUE THREAD

**Issue by gravesjohnr** [fondberg/spotcast#523]
### The problem

Perhaps I'm doing something wrong, but I can't seem to setup the new Home Assistant Voice PE device.

I have casting working for other media players and I can cast things like Radio to my Voice PE.

Config I tried for Spotcast to send to V PE:
```
action: spotcast.start
metadata: {}
data:
  limit: 20
  force_playback: false
  random_song: false
  repeat: "off"
  shuffle: false
  offset: 0
  start_position: 0
  ignore_fully_played: false
  entity_id: **media_player.home_assistant_voice_098efd_media_player**
  uri: spotify:track:5wIjkyWuwijp6GC88vak5Q
```
Config I use for a radio stream:
```
action: media_player.play_media
metadata: {}
data:
  media_content_id: media-source://radio_browser/a64d61e0-48b9-4bfc-a57c-0117f58b9ea4
  media_content_type: audio/aac
target:
  device_id: c07566d0830a9a061442108bd20c52e4
  entity_id: **media_player.home_assistant_voice_098efd_media_player**

``` 
The error I get is:
Error running action
device_name is empty

When I add a device_name by adding this line to the YAML
device_name: Office Home Assistant Voice

I get the error:
Could not find device with name Office Home Assistant Voice

Perhaps I am not understanding the configuration correctly  It seems like I really need to provide the device_id, not device_name or for some reason it can't do the mapping.

Help please.  I'd really love to be able to play Spotify on my new PE! 

Thank you.
-John

### System Health details

Version 	core-2025.2.2
Installation type 	Home Assistant OS
Development 	false
Supervisor 	true
Docker 	true
User 	root
Virtual environment 	false
Python version 	3.13.1
Operating system family 	Linux
Operating system version 	6.6.62-haos-raspi
CPU architecture 	aarch64
Timezone 	America/Denver
Configuration directory 	/config

### Spotcast Version

v4.0.0

### What type of installation are you running?

Home Assistant OS

### Example YAML snippet

```yaml

```

### Anything in the logs that might be useful for us?

```txt

```
