### ISSUE TITLE
Automations not working reliably

### ISSUE THREAD

**Issue by CHR15714N** [fondberg/spotcast#537]
### The problem

The automation set as working routine only works sometime. The routine turns on my Sony Bravia TV and should start playing Spotify, which happens only sometimes.

Executed: April 12, 2025 at 19:57:26
Error: Could not find `media_player.chris_bravia_w7mbjxn3rhgpd0vzkbqoluiw1_spotcast` in the managed integrations
Result:
params:
  domain: spotcast
  service: play_media
  service_data:
    media_player:
      device_id: b4566a6c2cba648bb9552c3c0c3e49fb
    spotify_uri: spotify:playlist:0eIsUEWsfagasfgBTIKMkIbA
    data:
      volume: 3
      random: true
      shuffle: true
    account: 01JRJF5Aasfgfsgsf5ZREWEC
  target: {}
running_script: false

## System Information

version | core-2025.4.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.13.2
os_name | Linux
os_version | 6.12.20-haos
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 5000
Installed Version | 2.0.5
Stage | running
Available Repositories | 1647
Downloaded Repositories | 4

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 15.1
-- | --
update_channel | stable
supervisor_version | supervisor-2025.04.0
agent_version | 1.7.2
docker_version | 28.0.4
disk_total | 30.8 GB
disk_used | 4.2 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | kvm
board | generic-aarch64
supervisor_api | ok
version_api | ok
installed_addons | Matter Server (7.0.0), File editor (5.8.0), Terminal & SSH (9.16.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 0
views | 2
mode | storage

</details>

<details><summary>Network Configuration</summary>

adapters | lo (disabled), enp0s11 (enabled, default, auto), hassio (disabled), docker0 (disabled), veth814668a (disabled), vethedf5274 (disabled), vethb1d6336 (disabled), vethcfa9f6e (disabled), veth836c5b6 (disabled), vethbf09457 (disabled), vethf4bb8b0 (disabled), veth2a2c879 (disabled)
-- | --
ipv4_addresses | lo (127.0.0.1/8), enp0s11 (192.168.0.93/24), hassio (172.30.32.1/23), docker0 (172.30.232.1/23), veth814668a (), vethedf5274 (), vethb1d6336 (), vethcfa9f6e (), veth836c5b6 (), vethbf09457 (), vethf4bb8b0 (), veth2a2c879 ()
ipv6_addresses | lo (::1/128), enp0s11 (2a02:810c:a10:a300:c6ef:5c95:981c:a571/64, fe80::9512:2d3e:ecf2:64c3/64), hassio (fe80::bc21:f5ff:fec1:e87d/64), docker0 (fe80::f811:93ff:fe32:47d8/64), veth814668a (fe80::dcd8:b0ff:fe60:fbc5/64), vethedf5274 (fe80::6c25:91ff:feee:6c42/64), vethb1d6336 (fe80::6c45:39ff:fe50:1786/64), vethcfa9f6e (fe80::6097:87ff:fe8c:256d/64), veth836c5b6 (fe80::4010:daff:feca:5e58/64), vethbf09457 (fe80::c9e:99ff:fe7b:f497/64), vethf4bb8b0 (fe80::b445:21ff:fe5f:6808/64), veth2a2c879 (fe80::28b2:caff:fe9b:3fac/64)
announce_addresses | 192.168.0.93, 2a02:810c:a10:a300:c6ef:5c95:981c:a571, fe80::9512:2d3e:ecf2:64c3

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | April 11, 2025 at 10:52
-- | --
current_recorder_run | April 12, 2025 at 13:52
estimated_db_size | 6.25 MiB
database_engine | sqlite
database_version | 3.48.0

</details>

<details><summary>Spotcast</summary>

Version | 5.0.0-b35
-- | --
W7mbjxn3rhgpd0vzkbqoluiw1 Is Default | true
W7mbjxn3rhgpd0vzkbqoluiw1 Public Endpoint | ok
W7mbjxn3rhgpd0vzkbqoluiw1 Public Token | healthy
W7mbjxn3rhgpd0vzkbqoluiw1 Private Endpoint | ok
W7mbjxn3rhgpd0vzkbqoluiw1 Private Token | healthy
W7mbjxn3rhgpd0vzkbqoluiw1 Product | premium

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

[home-assistant_spotcast_2025-04-12T17-58-01.735Z.log](https://github.com/user-attachments/files/19721148/home-assistant_spotcast_2025-04-12T17-58-01.735Z.log)

### Example YAML snippet

```yaml
alias: Morning Routine
description: ""
triggers:
  - trigger: time
    at: "05:30:00"
conditions:
  - condition: state
    entity_id: person.christian_rol
    state: home
actions:
  - action: remote.send_command
    data:
      command: WakeUp
      num_repeats: 10
      delay_secs: 0.5
      hold_secs: 1
    target:
      device_id:
        - f0296c07ac32ee08e6639e2808eb8ac2
  - delay:
      hours: 0
      minutes: 0
      seconds: 10
      milliseconds: 0
    enabled: true
  - action: remote.send_command
    data:
      command: PictureOff
      hold_secs: 1
    target:
      device_id:
        - f0296c07ac32ee08e6639e2808eb8ac2
    enabled: true
  - action: spotcast.play_media
    metadata: {}
    data:
      media_player:
        device_id: b4566a6c2cba648bb9552c3c0c3e49fb
      spotify_uri: spotify:playlist:0eIsUsDffLBTIKMkIbA
      data:
        volume: 3
        random: true
        shuffle: true
      account: 01JRJF5sfgafgs5ZREWEC
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - action: media_player.volume_set
    metadata: {}
    data:
      volume_level: 0.06
    target:
      device_id: 67e8c67b2a158dee10281908c2da1c13
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - action: media_player.volume_set
    metadata: {}
    data:
      volume_level: 0.09
    target:
      device_id: 67e8c67b2a158dee10281908c2da1c13
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - action: media_player.volume_set
    metadata: {}
    data:
      volume_level: 0.12
    target:
      device_id: 67e8c67b2a158dee10281908c2da1c13
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - action: media_player.volume_set
    metadata: {}
    data:
      volume_level: 0.15
    target:
      device_id: 67e8c67b2a158dee10281908c2da1c13
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - action: media_player.volume_set
    metadata: {}
    data:
      volume_level: 0.2
    target:
      device_id: 67e8c67b2a158dee10281908c2da1c13
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - action: media_player.volume_set
    metadata: {}
    data:
      volume_level: 0.3
    target:
      device_id: 67e8c67b2a158dee10281908c2da1c13
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - action: media_player.volume_set
    metadata: {}
    data:
      volume_level: 0.4
    target:
      device_id: 67e8c67b2a158dee10281908c2da1c13
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - action: media_player.volume_set
    metadata: {}
    data:
      volume_level: 0.6
    target:
      device_id: 67e8c67b2a158dee10281908c2da1c13
mode: single
```

### Anything in the logs that might be useful for us?

```txt
Executed: April 12, 2025 at 19:57:26
Error: Could not find `media_player.chris_bravia_w7mbjxn3rvasdvzkbqoluiw1_spotcast` in the managed integrations
Result:
params:
  domain: spotcast
  service: play_media
  service_data:
    media_player:
      device_id: b4566a6c2cbaasgd2c3c0c3e49fb
    spotify_uri: spotify:playlist:0eIsUEW4asfgIKMkIbA
    data:
      volume: 3
      random: true
      shuffle: true
    account: 01JRJF5A6BDsagsfgaREWEC
  target: {}
running_script: false
```
