### ISSUE TITLE
400 error on login.

### ISSUE THREAD

**Issue by alanranciato** [fondberg/spotcast#84]
Have tested creds on spotify web player as well as spotify dev portal, but still getting the following error:

**_"400 Client Error: Bad Request for url: https://accounts.spotify.com/api/login"_**

configuration in configuration.yaml is: 
```
spotcast:
  username: !secret spotify_username
  password: !secret spotify_password
  accounts:
      alan:
        username: !secret spotify_username
        password: !secret spotify_password
```
Have tried with and without the `accounts:` section.  Made sure both secrets and config don't contain any leading/trailing spaces or other characters.

Running hass.io .108.9 and spotcast 2.91 (says 2.92 is available but requires hass .109 (which isn't available yet).  Ubuntu 18.04 on NUC.
